In [ ]:
ПОГРУЖЕНИЕ В DATA ANALYST

In [6]:
import numpy as np

In [15]:
x = np.arange(10)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [17]:
np.savez("x_y-squared.npz", x_axis=x, y_axis=y)


In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
x          ndarray    10: 10 elems, type `int32`, 40 bytes
y          ndarray    10: 10 elems, type `int32`, 40 bytes


In [ ]:
% и ! (только в jupyter) -это способ запуска команды оболочки из jupyter.

In [ ]:
Знак ! ставится , что бы запустить команду в терминале
!pip install numpy